### PR TITLE
Add an ability to predefine common download paths

### PR DESCRIPTION
**Pull request by fastiuk**
* Add predefine config file: preconfig.json
* Defined one parameter COMMON_PATH that holds predefined common path in the next format:
  /path1/dir/bla;/path2/dir2/lol Paths should be semicolon separated
  
The problem I resolved here is that the common paths we saved are stored only in local storage and not shared between your computers.
This feature allows users to define preconfigured paths that will be available everywhere.

### CODE REVIEW

**Comment by fastiuk** [comment]
@johman10 could you please review it?

**Comment by johman10** [comment]
@fastiuk thanks a lot for the PR I was thinking about doing something like this but never really came around to it. This is actually quite a good solution to the problem presented in https://github.com/johman10/flood-for-transmission/issues/434. It's definitly not perfect yet, but it's a great first step towards that state where config can be shared.

The changes I made based on your PR:
- Use comma seperation and trimming of values before showing, also make sure there are no empty string left
- Properly wait for the promise to resolve before showing or storing the paths
- Rename preconf.json to config.json
- Allow for overwriting on a per browser basis like before. This means that the config will only be read when there is no value stored in the browser yet. To be honest I'm not 100% sure if this should be the expected behavior but for now I would prefer to load the variables still into the browser like before. Perhaps until this grows to become a bigger, more consistent pattern through the UI.

Let me know what you think. I will keep this behind for a little longer to allow you to respond to those suggestions.

**Review by fastiuk — COMMENTED** [review]
Yes, all the changes looks good to me

**Comment by johman10** [comment]
@fastiuk once again thank you for your contribution. This PR has now been shipped. If you update to the latest version you can start using it (and all other features).

**Comment by fastiuk** [comment]
> @fastiuk once again thank you for your contribution. This PR has now been shipped. If you update to the latest version you can start using it (and all other features).

Nice, thanks :)

**Pull request merged**
